# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code,
# and run tests across different versions of node. It includes checking commitizen, prettier, and eslint.

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - name: Check Commitizen
        run: npx commitizen --version

      - name: Check Prettier
        run: npx prettier --version

      - name: Check ESLint
        run: npx eslint --version
